### ISSUE TITLE
Error when following read me steps

### ISSUE THREAD

**Issue by merrua** [behave-contrib/behave-html-formatter#20]
Hi Bittner,

I was testing this out in order to see if we could use it for a project. It looks like the readme steps may be incorrect? 

IDE: Current visual studio code.
**Steps to reproduce**: 
1) I created a brand new behave project and installed only behave and behave-html-formatter using pip. 
2) I created the basic feature/step file from behave tutorial https://behave.readthedocs.io/en/stable/tutorial.html
3) I created the behave.ini file 
`# -- FILE: behave.ini
# Define ALIAS for HtmlFormatter.
[behave.formatters]
html = behave_html_formatter:HTMLFormatter`

4) I ran behave -f html and received the error
`usage: behave [options] [ [DIR|FILE|FILE:LINE] ]+
behave: error: format=html is unknown`

I can run behave -f json fine. 
No version of html shows if I run behave -f help

**Comment by bittner** [comment]
First, the configuration in (one of) behave's config file(s) is optional. If you don't get this working you should still be able to run the formatter by using the entire formatter module path. The documentation, as linked in the README, explains this by example.

If you're unsure whether you've configured the formatter alias correctly (i.e. whether it's getting recognized) you can run the formatter help, which lists all the ones that have been detected:

```console
behave -f help
```

It might be that the configuration file is not read, because it's in some weird location. (I guess Windows is susceptible to this kind of confusions. Do you use Windows?) -- You can ask behave for verbose output to help you understand such a situation, e.g.

```console
behave --verbose
```
